# Generated by Django 5.2.17 on 2026-08-26 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_new_cards_limit', models.PositiveIntegerField(default=20, help_text='Maximum new cards to introduce per day')),
                ('daily_review_limit', models.PositiveIntegerField(default=100, help_text='Maximum review cards per day')),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('last_studied_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
