# Generated by Django 5.2.17 on 2026-08-26 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(choices=[('indigo', 'Indigo'), ('blue', 'Blue'), ('emerald', 'Emerald'), ('amber', 'Amber'), ('rose', 'Rose'), ('purple', 'Purple'), ('teal', 'Teal')], default='indigo', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Allow other users to view/clone this deck')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
