# Generated by Django 5.2.17 on 2026-08-26 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='color',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='is_public',
        ),
    ]
