# Generated by Django 5.2.17 on 2026-08-26 05:00

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_remove_deck_color_remove_deck_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='description',
            field=apps.core.fields.EncryptedTextField(blank=True, help_text='Deck description (Encrypted at rest)'),
        ),
    ]
