# Generated by Django 5.2.17 on 2026-08-26 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Again'), (2, 'Hard'), (3, 'Good'), (4, 'Easy')])),
                ('duration_ms', models.PositiveIntegerField(default=0, help_text='Time taken to answer in milliseconds')),
                ('prev_interval', models.DecimalField(decimal_places=3, max_digits=8)),
                ('new_interval', models.DecimalField(decimal_places=3, max_digits=8)),
                ('prev_ease', models.DecimalField(decimal_places=2, max_digits=4)),
                ('new_ease', models.DecimalField(decimal_places=2, max_digits=4)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
