# Generated by Django 5.2.17 on 2026-08-26 04:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField(help_text='Question / Prompt (Supports Markdown & KaTeX $...$)')),
                ('back', models.TextField(help_text='Answer / Solution (Supports Markdown & KaTeX $...$)')),
                ('hint', models.CharField(blank=True, help_text='Optional hint displayed on front', max_length=255)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags e.g. vocab, chapter1', max_length=255)),
                ('state', models.CharField(choices=[('NEW', 'New'), ('LEARNING', 'Learning'), ('REVIEW', 'Review'), ('SUSPENDED', 'Suspended')], default='NEW', max_length=20)),
                ('ease_factor', models.DecimalField(decimal_places=2, default=2.5, max_digits=4)),
                ('interval_days', models.DecimalField(decimal_places=3, default=0.0, max_digits=8)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('lapses', models.PositiveIntegerField(default=0)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='decks.deck')),
            ],
            options={
                'ordering': ['due_date', 'created_at'],
            },
        ),
    ]
