# Generated by Django 5.2.17 on 2026-08-26 05:00

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='back',
            field=apps.core.fields.EncryptedTextField(help_text='Answer / Solution (Encrypted at rest)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='front',
            field=apps.core.fields.EncryptedTextField(help_text='Question / Prompt (Encrypted at rest)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='hint',
            field=apps.core.fields.EncryptedCharField(blank=True, help_text='Optional hint (Encrypted at rest)', max_length=1024),
        ),
        migrations.AlterField(
            model_name='card',
            name='tags',
            field=apps.core.fields.EncryptedCharField(blank=True, help_text='Comma-separated tags (Encrypted at rest)', max_length=1024),
        ),
    ]
